### ISSUE TITLE
[FIX] automatic-datetime

### ISSUE THREAD

**Issue by Ankur-Datta-4** [Ankur-Datta-4/SuspaceJavaPOC#4]
The creation-time of post and message, needs to be automatically set to currentDateTime while creation of the object.
But, it is getting set to null / Not getting set

**Comment by phaneesh707** [comment]
I'm trying to fix the issue, so how should I start the server to test it?

**Comment by Ankur-Datta-4** [comment]
[CLOSED] by @phaneesh707  on #5
